---
# file: roles/common/tasks/main.yml
- name: Add docker apt key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D
- name: Update apt with repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present
- name: Inform package manager
  apt: update_cache=yes 
- name: Install Docker
  apt: pkg=docker-engine force=yes 

