---
# file: targets.yml

- hosts: Targets
  become: true
  become_user: root
  gather_facts: false
  vars:
    ROOTGOINSTALL:
      /usr/local/go
    EXPGOPATH:
      GOPATH: /usr/local/gows
    ROOTGOPATH:
      /usr/local/gows
    ROOTGOCODE:
      /vagrant/gocode/src
  roles:
  - common

