---
# file: targets.yml

- hosts: Targets
  become: true
  become_user: root
  gather_facts: false
  vars:
    USRLOCALPATH:
      /usr/local
    ROOTGOINSTALL:
      /usr/local/go
    EXPGOROOT_BOOTSTRAP:
      GOROOT_BOOTSTRAP: /usr/local/go1.4
    EXPGOPATH:
      GOPATH: /usr/local/gows
    ROOTGOPATH:
      /usr/local/gows
    ROOTGOCODE:
      /vagrant/gocode/src
    ROOTDOCKER:
      /vagrant/docker
  roles:
  - common
